apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-report-cs-backend-deployment
  namespace: learner-report
  labels:
    app: learner-report-cs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner-report-cs-backend
  template:
    metadata:
      labels:
        app: learner-report-cs-backend
    spec:
      containers:
      - name: learner-report-cs-backend
        image: crashrik/learner-report-backend:latest # Replace with your actual image
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: learner-report-cs-backend-configmap
        - secretRef:
            name: learner-report-cs-backend-secret