apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-report-cs-frontend-deployment
  namespace: learner-report
  labels:
    app: learner-report-cs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner-report-cs-frontend
  template:
    metadata:
      labels:
        app: learner-report-cs-frontend
    spec:
      containers:
      - name: learner-report-cs-frontend
        image: crashrik/learner-report-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: learner-report-cs-frontend-configmap
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5