apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learner-report-cs-frontend-ingress
  namespace: learner-report
  labels:
    app: learner-report-cs-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: frontend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learner-report-cs-frontend-service
                port:
                  number: 80
