{{- $namespace := .Values.global.namespace -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-report-backend
  namespace: {{ $namespace }}
  labels:
    app: learner-report-backend   
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: learner-report-backend     
  template:
    metadata:
      labels:
        app: learner-report-backend       
    spec:
      containers:
      - name: learner-report-backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        env:
        - name: ATLAS_URI
          value: {{ .Values.backend.env.ATLAS_URI | quote }}
        - name: HASH_KEY
          value: {{ .Values.backend.env.HASH_KEY | quote }}
        - name: JWT_SECRET_KEY
          value: {{ .Values.backend.env.JWT_SECRET_KEY | quote }}
        resources:
{{ toYaml .Values.backend.resources | indent 10 }}