{{- if and .Values.backend.enabled .Values.backend.ingress.enabled }}
{{- $namespace := .Values.global.namespace -}}
{{- $environment := .Values.global.environment -}}
{{- $backendHost := index .Values.environments $environment "backend" "host" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.backend.name }}-ingress
  namespace: {{ $namespace }}
  labels:
    app: {{ .Values.backend.name }}
    component: backend
    chart: {{ include "learner-report.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- with .Values.backend.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.backend.ingress.className }}
  ingressClassName: {{ .Values.backend.ingress.className }}
  {{- end }}
  {{- if .Values.backend.ingress.tls }}
  tls:
    {{- range .Values.backend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - host: {{ $backendHost }}
    http:
      paths:
      - path: /student
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /careerservice
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /batch
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /attendance
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /company
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /placement
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /capstoneProgress
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /assessment
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /assignment
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /capstone
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
{{- end }}
