{{- $namespace := .Values.global.namespace -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-report-frontend
  namespace: {{ $namespace }}
  labels:
    app: learner-report-frontend    
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: learner-report-frontend      
  template:
    metadata:
      labels:
        app: learner-report-frontend        
    spec:
      containers:
      - name: learner-report-frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_BASE_URL
          value: {{ .Values.frontend.env.REACT_APP_API_BASE_URL | quote }}
        resources:
{{ toYaml .Values.backend.resources | indent 10 }}