{{- $namespace := .Values.global.namespace -}}
---
apiVersion: v1
kind: Service
metadata:
  name: learner-report-frontend
  namespace: {{ $namespace }}
  labels:
    app: learner-report-frontend   
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
  selector:
    app: learner-report-frontend   